import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {carvePassage,landingRoute,projectionXZ} from './model-tools.js';
import {GLTFExporter} from 'three/addons/exporters/GLTFExporter.js';

const $=id=>document.getElementById(id);
const nodes=[
 {name:'断崖朝圣道',short:'朝圣道',p:[-44,2,38],size:[13,14],text:'狭窄的石阶沿断崖爬升。远处的礼拜堂压在天际线上，而一座高桥从头顶掠过。',design:'先展示终点，再隐藏通路；用窄入口建立尺度与方向。'},
 {name:'旧祈祷所',short:'祈祷所',p:[-30,8,12],size:[20,19],text:'第一处余烬。一扇门从另一侧锁着，升降梯停在遥不可及的高处。此刻，这里只是死路边的避难所。',design:'两条暂不可用的捷径提前露面，把回归变成可期待的事件。'},
 {name:'倾斜旧街',short:'旧街',p:[-4,10,34],size:[22,17],text:'房屋挤出一条弯折街道。敌人可从侧巷夹击；街尾忽然下沉，把钟楼从视野中抹去。',design:'压缩视野后转折下行；支巷奖励与主路保持视觉关联。'},
 {name:'无光蓄水池',short:'蓄水池',p:[22,-2,22],size:[23,22],text:'脚步落到旧城之下。柱廊切断视线，浅水反射唯一的天光；沿排水渠走向东侧地下墓室。',design:'用最低点制造迷失与压迫；桥下的水渠解释地上、地下关系。'},
 {name:'守墓人庭院',short:'墓庭',p:[38,2,-6],size:[19,24],text:'窄渠通向开阔墓庭。中央精英敌人守住长阶，侧边墓碑给出绕行与短暂掩护。',design:'低压探索转为开阔遭遇战；上行长阶重新露出钟楼目标。'},
 {name:'灰枝回廊',short:'回廊',p:[19,15,-27],size:[24,20],text:'第二处余烬。推开回廊西侧的铁门，穿过横桥，竟直接回到旧祈祷所上方的石阶。',design:'捷径 A 在远侧解锁；把长距离探索折回初始中枢，兑现第一次空间惊喜。'},
 {name:'失声钟楼',short:'钟楼',p:[0,27,-36],size:[15,16],text:'残钟悬在空洞的塔身里。回看可同时辨认旧街、水池与入口；高处的风取代了地下的回声。',design:'在高点提供全景认知奖励，用俯瞰把此前碎片拼成完整地图。'},
 {name:'悬空赎罪桥',short:'高架桥',p:[-30,28,12],size:[13,12],text:'终于走上开场头顶的高桥。扳下升降梯拉杆，二十米之下就是最初休息的那簇余烬。',design:'捷径 B 连接上下重叠空间；最终挑战前建立短跑图回路。'},
 {name:'终焉礼拜堂',short:'礼拜堂',p:[-31,37,-27],size:[25,27],text:'绕过最后的朝圣长阶，金色雾门之后是空旷的圆形祭坛。起点可见的终点，如今就在脚下。',design:'雾门前保留准备平台；用对称与开阔收束一路不对称的探索。'}
];
const chains=[
 [[-44,2,38],[-44,2,29],[-38,5,25],[-30,8,24],[-30,8,12]],
 [[-30,8,12],[-18,8,12],[-18,10,30],[-13,10,34],[-4,10,34]],
 [[-4,10,34],[10,10,34],[12,10,37],[12,4,49],[18,4,49],[18,-2,38],[18,-2,22],[22,-2,22]],
 [[22,-2,22],[34,-2,22],[38,2,9],[38,2,-6]],
 [[38,2,-6],[38,2,-20],[42,8,-32],[38,15,-44],[33,15,-44],[33,15,-27],[19,15,-27]],
 [[19,15,-27],[19,15,-41],[13,21,-49],[0,27,-49],[0,27,-36]],
 [[0,27,-36],[-13,27,-36],[-25,28,-17],[-30,28,12]],
 [[-30,28,12],[-44,28,12],[-47,28,9],[-48,31,1],[-48,31,-1],[-48,35,-10],[-46,35,-11],[-42,37,-12],[-31,37,-12],[-31,37,-27]]
].map(landingRoute);
const shortcuts=[landingRoute([[19,15,-27],[19,15,-18],[4,15,-8],[-12,15,-8],[-26,8,0],[-26,8,12],[-30,8,12]]),[[-30,28,12],[-30,28,15.8],[-34,28,15.8],[-34,8,15.8],[-30,8,15.8],[-30,8,12]]];
const branches=[[[-4,10,34],[8,10,34],[8,10,43],[4,10,46]],[[38,2,-6],[49,2,-4],[49,2,-15]]];
const renderer=new THREE.WebGLRenderer({canvas:$('world'),antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.28;
const scene=new THREE.Scene();scene.background=new THREE.Color('#15272e');scene.fog=new THREE.FogExp2('#15272e',.0028);
const camera=new THREE.PerspectiveCamera(innerWidth<650?52:39,innerWidth/innerHeight,.1,1000);camera.position.set(133,115,158).multiplyScalar(innerWidth<650?1.35:1);
const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(-2,12,0);controls.enableDamping=true;controls.dampingFactor=.065;controls.maxPolarAngle=Math.PI*.48;controls.minDistance=12;controls.maxDistance=520;controls.update();
const hemi=new THREE.HemisphereLight('#b5d5db','#313d34',2.2);scene.add(hemi);const sun=new THREE.DirectionalLight('#ecd5a6',3.7);sun.position.set(-40,100,45);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-95,right:95,top:100,bottom:-90,near:1,far:250});sun.shadow.bias=-.0006;sun.shadow.normalBias=.3;scene.add(sun);const rim=new THREE.DirectionalLight('#638fa6',2.1);rim.position.set(45,45,-70);scene.add(rim);
const model=new THREE.Group();model.name='Ashbell Sanctuary - Original Level Blockout';scene.add(model);const architecture=new THREE.Group();architecture.name='Architecture';model.add(architecture);const cutParts=[];const roadGroup=new THREE.Group();roadGroup.name='Traversable stairs and bridges';model.add(roadGroup);const routeGroup=new THREE.Group();routeGroup.name='Main route overlay';scene.add(routeGroup);const shortGroup=new THREE.Group();shortGroup.name='Shortcut overlays';scene.add(shortGroup);
const terrain=new THREE.Group();terrain.name='Terraced foundations with real tunnel';model.add(terrain);
const mats={};function mat(name,c,rough=1,metal=0){return mats[name]=new THREE.MeshStandardMaterial({color:c,roughness:rough,metalness:metal,flatShading:true})}
mat('stone','#8c8d7e');mat('edge','#a4a18e');mat('dark','#526569');mat('roof','#394f55');mat('floor','#aaa591');mat('rock','#3e5358');mat('rock2','#53676a');mat('earth','#344a49');mat('iron','#384c4c',.6,.5);mat('gold','#b59861',.4,.5);mat('wood','#756a51');mat('bone','#bab29a');mat('brick','#727f79');mat('red','#91584b');
const water=new THREE.MeshStandardMaterial({color:'#376c70',roughness:.22,metalness:.35,transparent:true,opacity:.8});const ember=new THREE.MeshBasicMaterial({color:'#ffd084'});const mainMat=new THREE.MeshBasicMaterial({color:'#ffc76d',transparent:true,opacity:.95,depthTest:false,toneMapped:false});const shortMat=new THREE.MeshBasicMaterial({color:'#72e8c8',transparent:true,opacity:.35,depthTest:false,toneMapped:false});const gateMat=new THREE.MeshStandardMaterial({color:'#bd9151',emissive:'#95713a',emissiveIntensity:.6,transparent:true,opacity:.26,side:THREE.DoubleSide});
let seed=371;function rand(){seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296}
const boxgeo=new THREE.BoxGeometry(1,1,1);function mesh(g,m,x,y,z,group=architecture){let o=new THREE.Mesh(g,m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;o.name=group.name+' '+g.type+' @ '+[x,y,z].join(',');group.add(o);return o}
function box(x,y,z,w,h,d,m=mats.stone,group=architecture,cut=false){let o=mesh(boxgeo,m,x,y,z,group);o.scale.set(w,h,d);if(cut)cutParts.push(o);return o}
function cylinder(x,y,z,r,h,m=mats.stone,n=10,rt=r,group=architecture){return mesh(new THREE.CylinderGeometry(rt,r,h,n),m,x,y,z,group)}
function rail(a,b,height=.85,m=mats.iron,group=architecture){const A=new THREE.Vector3(...a),B=new THREE.Vector3(...b);const obj=box(...A.clone().add(B).multiplyScalar(.5).toArray(),.16,height,A.distanceTo(B),m,group);obj.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,1),B.sub(A).normalize());return obj}
function arch(x,y,z,width=4,height=6,depth=1,rot=0){const g=new THREE.Group();g.position.set(x,y,z);g.rotation.y=rot;architecture.add(g);const radius=width/2;let h=height-radius;box(-radius-.35,h/2,0,.7,h,depth,mats.edge,g);box(radius+.35,h/2,0,.7,h,depth,mats.edge,g);for(let i=0;i<11;i++){let a=i/11*Math.PI+.008,b=(i+1)/11*Math.PI-.008;const shape=new THREE.Shape();shape.moveTo(Math.cos(a)*radius,Math.sin(a)*radius);shape.lineTo(Math.cos(a)*(radius+.65),Math.sin(a)*(radius+.65));shape.lineTo(Math.cos(b)*(radius+.65),Math.sin(b)*(radius+.65));shape.lineTo(Math.cos(b)*radius,Math.sin(b)*radius);shape.closePath();let voussoir=mesh(new THREE.ExtrudeGeometry(shape,{depth,bevelEnabled:false}),mats.edge,0,h,-depth/2,g);voussoir.name='Arch voussoir';}return g}
function battlements(x,y,z,w,d){for(let i=-w/2+.6;i<w/2;i+=2){box(x+i,y,z-d/2,.85,1,1,mats.edge);box(x+i,y,z+d/2,.85,1,1,mats.edge)}for(let i=-d/2+1.4;i<d/2;i+=2){box(x-w/2,y,z+i,1,1,.85,mats.edge);box(x+w/2,y,z+i,1,1,.85,mats.edge)}}
function tower(x,y,z,r=3,h=12,roof=true){cylinder(x,y+h/2,z,r,h,mats.stone,8);cylinder(x,y+.4,z,r+1,.8,mats.edge,8);cylinder(x,y+h-.2,z,r+.4,.6,mats.edge,8);if(roof){let o=cylinder(x,y+h+3,z,r+.7,6,mats.roof,8,0);cutParts.push(o)}for(let k=0;k<4;k++){let t=k*Math.PI/2;let o=box(x+Math.sin(t)*(r+.05),y+h*.65,z+Math.cos(t)*(r+.05),.6,2.3,.15,mats.dark);o.rotation.y=t}}
function torch(x,y,z,large=false){cylinder(x,y+.5,z,large?.85:.3,1,mats.iron,6);const fire=mesh(new THREE.OctahedronGeometry(large?.8:.35),ember,x,y+1.3,z);fire.scale.y=1.9;flames.push(fire);if(large){const l=new THREE.PointLight('#ffb24f',13,13,1.5);l.position.set(x,y+2,z);scene.add(l);cylinder(x,y+.1,z,1.5,.2,mats.dark,12)}}
const flames=[];
// Continuous approach levels: slab edges are reached only after each stair flight levels out.
nodes.forEach((n,i)=>{const [x,y,z]=n.p,[w,d]=n.size;const bottom=-16,startMesh=terrain.children.length;
 if(i!==7){box(x,(y+bottom)/2-1,z,w*.92,y-bottom-2,d*.92,mats.rock,terrain);for(let j=0;j<8;j++){let a=j/8*Math.PI*2,r=1+rand()*1.4;let o=cylinder(x+Math.cos(a)*w*.39,(y+bottom)/2-2,z+Math.sin(a)*d*.39,r+2.1,y-bottom-3,j%2?mats.rock:mats.rock2,6,r,terrain);o.rotation.y=rand()*3;}}
 let rectangles=[[x-w/2,x+w/2,z-d/2,z+d/2]];
 if(i===7){const [l,r,north,south]=[-35.8,-32.2,14,17.6];rectangles=[[x-w/2,l,z-d/2,z+d/2],[r,x+w/2,z-d/2,z+d/2],[l,r,z-d/2,north],[l,r,south,z+d/2]];}
 for(const [l,r,north,south] of rectangles){box((l+r)/2,y-1.04-(i===3?.7:0),(north+south)/2,r-l,1.6,south-north,mats.brick,terrain);box((l+r)/2,y-.12-(i===3?.7:0),(north+south)/2,r-l,.24,south-north,mats.floor,terrain);}
 // Thin facade string courses stay beneath walking level and avoid the lift opening.
 if(i!==7)for(let yy=y-2;yy>-11;yy-=5){box(x,yy,z-d/2-.025,w,.22,.28,mats.dark,terrain);box(x+w/2+.025,yy,z,.28,.22,d,mats.dark,terrain);}
 terrain.children.slice(startMesh).forEach(o=>o.userData.zone=i);
});
const roadSpecs=[...chains.map(points=>({points,width:3.6})),{points:shortcuts[0],width:3.6},...branches.map(points=>({points,width:2.8})),{points:shortcuts[1].slice(0,3),width:2.8},{points:shortcuts[1].slice(3),width:2.8}];
const roadSegments=[];for(const spec of roadSpecs)for(let i=0;i<spec.points.length-1;i++)roadSegments.push({a:spec.points[i],b:spec.points[i+1],width:spec.width});
function onPlatform(p,margin=0){return nodes.some(n=>Math.abs(n.p[1]-p[1])<.05&&Math.abs(n.p[0]-p[0])<n.size[0]/2-margin&&Math.abs(n.p[2]-p[2])<n.size[1]/2-margin)}
function railAllowed(p,own){if(onPlatform(p,.45))return false;return !roadSegments.some(seg=>{if(seg===own)return false;let q=projectionXZ(p,seg.a,seg.b);return q.distance<seg.width/2+.32&&Math.abs(q.y-p[1])<2.6})}
function supportAllowed(p,top){return !roadSegments.some(seg=>{let q=projectionXZ(p,seg.a,seg.b);return q.distance<seg.width/2+.8&&q.y<top-1.1&&q.y>-16});}
// Junction-aware balustrades leave openings wherever another route meets the walkway.
for(const seg of roadSegments){let a=new THREE.Vector3(...seg.a),b=new THREE.Vector3(...seg.b),flat=Math.hypot(b.x-a.x,b.z-a.z);if(flat<.01)continue;let delta=b.y-a.y,width=seg.width,angle=Math.atan2(b.x-a.x,b.z-a.z),count=Math.max(Math.ceil(Math.abs(delta)/.24),Math.ceil(flat/2));
 for(let k=0;k<count;k++){let p=a.clone().lerp(b,(k+.5)/count),surface=Math.max(a.y+delta*k/count,a.y+delta*(k+1)/count);if(Math.abs(delta)<.01&&onPlatform(p.toArray(),width*.55))continue;let o=box(p.x,surface-.34,p.z,width,.68,flat/count+.015,mats.floor,roadGroup);o.rotation.y=angle;}
 const perp=new THREE.Vector3(b.z-a.z,0,a.x-b.x).normalize().multiplyScalar(width/2+.06);let n=Math.ceil(flat/.8);
 for(let sign of [-1,1]){let run=null;const finish=()=>{if(run&&run.last.distanceTo(run.start)>.25){let aa=run.start.clone(),bb=run.last.clone();aa.y+=1.05;bb.y+=1.05;rail(aa.toArray(),bb.toArray(),.26,mats.dark,roadGroup);let npost=Math.max(1,Math.ceil(aa.distanceTo(bb)/3.5));for(let k=0;k<=npost;k++){let p=aa.clone().lerp(bb,k/npost);box(p.x,p.y-.5,p.z,.24,1.25,.24,mats.edge,roadGroup)}}run=null};
  for(let k=0;k<n;k++){let aa=a.clone().lerp(b,k/n).addScaledVector(perp,sign),bb=a.clone().lerp(b,(k+1)/n).addScaledVector(perp,sign);if(railAllowed(aa.toArray(),seg)&&railAllowed(bb.toArray(),seg)){if(!run)run={start:aa,last:bb};else run.last=bb}else finish()}finish();}
 if(flat>8){let n=Math.floor(flat/10);for(let k=0;k<n;k++){let p=a.clone().lerp(b,(k+.5)/n);if(onPlatform(p.toArray(),-.5))continue;for(let sign of [-1,1]){let pp=p.clone().addScaledVector(perp,sign*.8);if(supportAllowed(pp.toArray(),p.y)){let h=p.y+15;box(pp.x,p.y-.8-h/2,pp.z,.95,h,.95,mats.dark,roadGroup);box(pp.x,p.y-1.3,pp.z,1.5,.5,1.5,mats.edge,roadGroup)}}}}
}
// Entrance: broken portal, roadside graves and a visible high destination.
arch(-44,2,43,4,7,1.1);tower(-50,2,36,1.8,6,false);for(let k=0;k<6;k++){box(-48+(k%2)*8,2.7,32+Math.floor(k/2)*4,1.05,1.4,.35,mats.brick)}
// Hub: roofless chapel and a locked side connection. Leave the central walking axis open.
box(-39,11.2,11,1,6.4,16,mats.stone,architecture,true);box(-34.1,11.2,3,9.8,6.4,1,mats.stone,architecture,true);box(-22.1,11.2,3,2.2,6.4,1,mats.stone,architecture,true);arch(-26,8,3,5.6,6.4,1);box(-26,14.1,3,5.6,.6,1,mats.stone,architecture,true);arch(-30,8,21,5,7,1);for(let x of [-37,-22]){box(x,8.6,8,1.8,1.2,1,mats.wood);box(x,8.6,14,1.8,1.2,1,mats.wood)}torch(-36,8,5.5,true);tower(-39,8,3,2,8);
// Lower street: distinct staggered house masses with gable roofs.
function house(x,y,z,w,d,h,rotation=0){let g=new THREE.Group();g.name='Hollow old-town house';g.position.set(x,y,z);g.rotation.y=rotation;architecture.add(g);const wall=.45,door=1.6;for(let side of [-1,1])box(side*(w-wall)/2,h/2,0,wall,h,d,mats.stone,g,true);box(0,h/2,-d/2+wall/2,w,h,wall,mats.stone,g,true);for(let side of [-1,1])box(side*(w+door)/4,h/2,d/2-wall/2,(w-door)/2,h,wall,mats.stone,g,true);box(0,(h+3)/2,d/2-wall/2,door,h-3,wall,mats.stone,g,true);box(0,.025,0,w-.6,.05,d-.6,mats.dark,g);for(let side of [-1,1])box(side*.9,1.55,d/2+.05,.18,3.1,.2,mats.edge,g);box(0,3.15,d/2+.05,2,.22,.2,mats.edge,g);const shape=new THREE.Shape();shape.moveTo(-w/2-.35,0);shape.lineTo(w/2+.35,0);shape.lineTo(0,3.3);shape.closePath();const roof=mesh(new THREE.ExtrudeGeometry(shape,{depth:d+.7,bevelEnabled:false}),mats.roof,0,h,-d/2-.35,g);cutParts.push(roof);box(0,h+3.3,0,.18,.18,d+.85,mats.iron,g);for(let side of [-1,1])box(side*w*.27,h*.73,d/2+.05,.65,1.2,.13,mats.dark,g);box(w*.28,h+2.1,-d*.23,.7,3,.7,mats.brick,g)}
house(-10,10,39,5,5,6,.1);house(-2,10,40,5,5,8,-.08);house(4,10,39,4,5,5,.05);house(-7,10,28,5,4,5,Math.PI);house(1,10,28,5,4,7,Math.PI);torch(5,10,31);for(let k=0;k<4;k++)box(-13+k*2,10.4,39,1,.8,1,mats.wood);
// Cistern: open cutaway basin, water recessed below a connected dry causeway.
box(22,-2.3,24,21,.05,16,water);box(22,-2.13,22,22,.26,3.8,mats.edge);box(18,-2.13,28,3.8,.26,14,mats.edge);for(let x of [14,22,30])for(let z of [15,29]){cylinder(x,1,z,.75,6,mats.stone,8);cylinder(x,4.2,z,1.15,.55,mats.edge,8)}for(let x of [18,26]){arch(x,-2,15,6.5,7,1);arch(x,-2,29,6.5,7,1)}box(22,-1,12,23,2,1,mats.dark);box(13.4,-1,32,5.8,2,1,mats.dark);box(27,-1,32,13,2,1,mats.dark);arch(18,-2,32,4.6,5.8,1);torch(32,-2,24);
// Grave court: a legible central encounter and optional peripheral cover.
for(let k=0;k<14;k++){let side=k%2?-1:1;let x=38+side*(5+rand()*2),z=-15+Math.floor(k/2)*3;box(x,2.7,z,.9,1.4,.4,mats.bone);box(x,2.08,z+1,1.1,.15,1.7,mats.dark)}cylinder(38,2.15,-8,3,.3,mats.dark,12);const sentinel=mesh(new THREE.IcosahedronGeometry(1.1,0),mats.red,41,4,-8);sentinel.scale.y=1.8;arch(38,2,6,4,6,1);tower(45,2,-15,1.8,8,false);
// Cloister: perimeter arcades frame a quiet second sanctuary.
for(let x of [10,19,28]){arch(x,15,-34,7,6,.8);arch(x,15,-20,7,6,.8)}box(19,21.6,-34,25,.7,2,mats.dark,architecture,true);box(19,21.6,-20,25,.7,2,mats.dark,architecture,true);arch(30,15,-27,5.4,6,.8,Math.PI/2);arch(30,15,-33,3.4,5.4,.8,Math.PI/2);torch(25.5,15,-24,true);cylinder(13,15.3,-27,1.9,.6,mats.dark,10);cylinder(13,17.4,-27,.3,4,mats.wood,5,.15);for(let k=0;k<5;k++){let branch=box(13+Math.sin(k)*.7,18+k*.2,-27+Math.cos(k)*.7,.14,2,.14,mats.wood);branch.rotation.z=.7+k*.8}
// Bell tower: open vertical frame, hanging bell, distant silhouette.
for(let x of [-5,5])for(let z of [-41,-31]){box(x,35,z,1.5,16,1.5,mats.stone,architecture,true);box(x,27.5,z,2.1,1,2.1,mats.edge)}arch(0,35,-31,8,7,1.3);arch(0,35,-41,8,7,1.3);box(0,43,-36,12,1,12,mats.edge,architecture,true);let roof=cylinder(0,47,-36,9,7,mats.roof,4,0);roof.rotation.y=Math.PI/4;cutParts.push(roof);cylinder(0,39,-36,.15,5,mats.iron,6);cylinder(0,36.8,-36,2.2,2.6,mats.gold,12,.9);cylinder(0,35.4,-36,2.4,.3,mats.gold,12);cylinder(5,45,-41,.55,4,mats.gold,6,.08);
// Lift well is an actual opening in the upper slab, offset from the through-route.
for(let x of [-36,-32])for(let z of [13.8,17.8]){box(x,19,z,.32,23,.32,mats.iron);box(x,30.55,z,.65,.6,.65,mats.gold);}
const elevator=new THREE.Group();elevator.name='Moving lift carriage';elevator.position.set(-34,27.8,15.8);architecture.add(elevator);box(0,0,0,3.4,.4,3.4,mats.wood,elevator);for(let z of [-1.5,1.5])rail([-1.5,.9,z],[1.5,.9,z],.22,mats.iron,elevator);rail([-1.5,.9,-1.5],[-1.5,.9,1.5],.22,mats.iron,elevator);
rail([-36,30.2,13.8],[-32,30.2,13.8],.35);rail([-36,30.2,17.8],[-32,30.2,17.8],.35);box(-35.7,29.4,15.8,.15,2,.15,mats.iron);box(-26,29,10,.35,2,.35,mats.gold);
for(let [x,z] of [[-36,8],[-24,8],[-24,17]]){box(x,17.5,z,.9,19,.9,mats.dark);box(x,27,z,1.8,1,1.8,mats.edge);}
box(-32.25,27.88,15.8,.1,.24,3.4,mats.iron);
// Upper parapet gaps align to the bridge, exit stair and lift landing.
for(let x=-35.5;x<-24;x+=2){if(Math.abs(x+29)<3)continue;box(x,28.65,6,.9,1.3,.8,mats.edge)}for(let z=7;z<18;z+=2){if(Math.abs(z-12)<2.5)continue;box(-36.5,28.65,z,.8,1.3,.9,mats.edge)}
// Final hall: tall apse, flanking towers, forecourt, altar and a mist gate.
box(-31,42,-39,25,10,1.5,mats.stone,architecture,true);box(-43,41.5,-28,1,9,21,mats.stone,architecture,true);box(-19,41.5,-28,1,9,21,mats.stone,architecture,true);for(let z of [-36,-29,-22]){box(-44,41,z,2,8,2,mats.dark);box(-18,41,z,2,8,2,mats.dark);arch(-43,38,z,4,6,.7,Math.PI/2);arch(-19,38,z,4,6,.7,Math.PI/2)}arch(-31,37,-16,7,10,1.5);tower(-41,37,-17,2.5,14);tower(-21,37,-17,2.5,14);arch(-31,41,-39,6,9,.8);cylinder(-31,37.03,-28,7,.06,mats.dark,32);cylinder(-31,37.07,-28,6.3,.04,mats.edge,32);cylinder(-31,37.11,-28,5.8,.04,mats.brick,32);box(-31,38,-35,4,2,2,mats.bone);let boss=mesh(new THREE.OctahedronGeometry(1.3),mats.red,-31,39.5,-29);boss.scale.y=2;const mist=box(-31,40.5,-16,6,7,.15,gateMat);torch(-36,37,-14);torch(-26,37,-14);
// Reward landings now connect through genuine gaps between houses and graves.
box(4,9.66,46,5,.68,5,mats.floor);box(4,10.65,48,1.4,1.3,1,mats.gold);box(49,1.66,-15,5,.68,5,mats.floor);box(50.7,2.55,-16,1.1,1.1,1.1,mats.gold);
const gates=[];for(let k=0;k<8;k++){let bar=box(17.5+k*.43,16.8,-18,.1,3.6,.12,mats.iron);bar.userData.auditIgnore=true;gates.push(bar)}
// Masonry bridge arches reinforce the horizontal spans without intruding into paths.
for(let x of [-8,-1])arch(x,7,-8,6,7.4,2.4);arch(-10,17,-36,7,9,2.2);
// The former collision with the upper citadel is now a carved, five-metre-high passage.
const tunnelCuts=carvePassage(terrain,chains[6],5.7,5.5);
arch(-18.1,27.27,-27.92,5.5,5.2,1.15,-.56);arch(-25.85,28,-12.1,5.5,5.2,1.15,-.17);
torch(-20.5,27.6,-23.5);torch(-27.7,28,-8);
// Dark water plane, irregular loose rock and distant spires keep the model grounded.
const sea=mesh(new THREE.CircleGeometry(175,80),new THREE.MeshStandardMaterial({color:'#1b353c',roughness:.65,metalness:.3}),0,-18,0,model);sea.rotation.x=-Math.PI/2;for(let i=0;i<35;i++){let a=rand()*Math.PI*2,r=65+rand()*40,x=Math.cos(a)*r,z=Math.sin(a)*r;let rock=cylinder(x,-17+rand()*3,z,2+rand()*5,5+rand()*12,mats.rock,5,.4,model);rock.rotation.z=(rand()-.5)*.3}for(let i=0;i<7;i++){let z=-85-rand()*18,x=-65+i*21,h=8+rand()*21;let o=cylinder(x,-18+h/2,z,5+rand()*4,h,mats.earth,5,1,model);}
function linePath(points,material,group,dashed=false){for(let j=0;j<points.length-1;j++){let a=new THREE.Vector3(...points[j]),b=new THREE.Vector3(...points[j+1]);a.y+=.48;b.y+=.48;const len=a.distanceTo(b);if(dashed){let n=Math.ceil(len/1.6);for(let k=0;k<n;k++){let aa=a.clone().lerp(b,k/n),bb=a.clone().lerp(b,Math.min((k+.5)/n,1));let o=mesh(new THREE.CylinderGeometry(.065,.065,aa.distanceTo(bb),4),material,...aa.clone().add(bb).multiplyScalar(.5).toArray(),group);o.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),bb.sub(aa).normalize());o.renderOrder=8}}else{const curve=new THREE.LineCurve3(a,b);const obj=mesh(new THREE.TubeGeometry(curve,1,.14,4,false),material,0,0,0,group);obj.renderOrder=8;}if(len>6&&!dashed){let center=a.clone().lerp(b,.6),arrow=mesh(new THREE.ConeGeometry(.45,1.1,3),material,...center.toArray(),group);arrow.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),b.clone().sub(a).normalize());arrow.renderOrder=9}}}
chains.forEach(p=>linePath(p,mainMat,routeGroup));shortcuts.forEach(p=>linePath(p,shortMat,shortGroup,true));
const markers=nodes.map((n,i)=>{const e=document.createElement('button');e.className='marker';e.innerHTML=`<b>${String(i+1).padStart(2,'0')}</b><span>${n.short}</span>`;e.setAttribute('aria-label',n.name);e.onclick=()=>select(i);$('labels').appendChild(e);const btn=document.createElement('button');btn.className='step';btn.innerHTML=`<span class="num">${String(i+1).padStart(2,'0')}</span><strong>${n.short}</strong>`;btn.onclick=()=>select(i);$('timeline').appendChild(btn);return e});
const selectRing=mesh(new THREE.RingGeometry(2.1,2.25,48),new THREE.MeshBasicMaterial({color:'#f4d399',side:THREE.DoubleSide,depthTest:false}),0,0,0,scene);selectRing.rotation.x=-Math.PI/2;selectRing.renderOrder=10;
let selected=0,unlocked=false,cut=false,bright=false,routeVisible=true,view='overview',touring=false,paused=false,tourDistance=0,tween=null,toastTimer;
function select(i){selected=i;const n=nodes[i];$('chapter-num').textContent=`${String(i+1).padStart(2,'0')} / 09`;$('height').textContent=`海拔 ${n.p[1]>=0?'+':''}${n.p[1]} m`;$('chapter-title').textContent=n.name;$('chapter-text').textContent=n.text;$('chapter-design').textContent=n.design;markers.forEach((e,k)=>e.classList.toggle('active',i===k));Array.from($('timeline').children).forEach((e,k)=>e.classList.toggle('active',i===k));selectRing.position.set(n.p[0],n.p[1]+.4,n.p[2]);if(touring){tourDistance=nodeDistances[i];}}
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3400)}
function fly(pos,target){stopTour(false);tween={from:camera.position.clone(),to:new THREE.Vector3(...pos),startTarget:controls.target.clone(),target:new THREE.Vector3(...target),t:0};}
function setView(v){view=v;['overview','top'].forEach(id=>$(id).classList.toggle('active',id===v));if(v==='top'){fly([-2,innerWidth<650?310:235,1],[-2,5,0]);$('view-name').textContent='02 / PLAN VIEW';$('view-description').textContent='金色主线一路折返，青色捷径收紧探索半径。'}else{fly([133,115,158].map(v=>v*(innerWidth<650?1.35:1)),[-2,12,0]);$('view-name').textContent='01 / AXONOMETRIC';$('view-description').textContent='回望走过的路，发现脚下是旧日的屋顶。'}}
$('overview').onclick=()=>setView('overview');$('top').onclick=()=>setView('top');$('home').onclick=e=>{e.preventDefault();setView('overview');select(0)};$('focus').onclick=()=>{let p=nodes[selected].p;fly([p[0]+27,p[1]+24,p[2]+34],[p[0],p[1]+3,p[2]]);$('view-name').textContent=`DETAIL / ${nodes[selected].name}`};
$('section').onclick=()=>{cut=!cut;cutParts.forEach(o=>o.visible=!cut);$('section').classList.toggle('active',cut);toast(cut?'已隐藏高墙与屋顶，显露内部空间':'已恢复完整建筑体块')};$('routes').onclick=()=>{routeVisible=!routeVisible;routeGroup.visible=shortGroup.visible=routeVisible;$('routes').classList.toggle('active',routeVisible)};$('light').onclick=()=>{bright=!bright;hemi.intensity=bright?3.7:2.2;sun.intensity=bright?4.6:3.7;renderer.toneMappingExposure=bright?1.55:1.28;scene.background.set(bright?'#344950':'#15272e');scene.fog.color.copy(scene.background);$('light').classList.toggle('active',bright);$('light').textContent=bright?'暮色':'冷昼'};
$('unlock').onclick=()=>{unlocked=!unlocked;gates.forEach(o=>o.visible=!unlocked);shortMat.opacity=unlocked?1:.35;$('unlock').innerHTML=unlocked?'已开启捷径 · 点击复位 <span>↺</span>':'演示：开启两条捷径 <span>↗</span>';$('shortcut-note').innerHTML=unlocked?'A · 06 → 02，横桥侧门已开启<br>B · 08 ↔ 02，升降梯往复演示中':'A · 回廊侧门 → 旧祈祷所<br>B · 高架桥升降梯 → 旧祈祷所';toast(unlocked?'捷径 A 的侧门已打开，捷径 B 的升降梯已启动':'已恢复首次到达时的锁闭状态')};
$('help').onclick=()=>$('help-dialog').showModal();$('inspect-tunnel').onclick=()=>{$('help-dialog').close();fly([-2,37,-6],[-22,29,-23]);};$('inspect-lift').onclick=()=>{$('help-dialog').close();fly([-12,42,35],[-33,24,15]);};$('close-help').onclick=()=>$('help-dialog').close();$('help-dialog').onclick=e=>{if(e.target===$('help-dialog'))$('help-dialog').close()};
// Arc-length based guided route, with linear segments to avoid cutting through corners.
const tourPoints=[];const nodeDistances=[0];let runningLength=0;chains.forEach((chain,i)=>{chain.forEach((p,j)=>{if(tourPoints.length&&j===0)return;if(tourPoints.length)runningLength+=new THREE.Vector3(...p).distanceTo(new THREE.Vector3(...tourPoints[tourPoints.length-1]));tourPoints.push(p)});nodeDistances.push(runningLength)});const segments=[];let total=0;for(let i=0;i<tourPoints.length-1;i++){const a=new THREE.Vector3(...tourPoints[i]),b=new THREE.Vector3(...tourPoints[i+1]),l=a.distanceTo(b);segments.push({a,b,l,start:total});total+=l}
function sample(d){d=Math.max(0,Math.min(total,d));const s=segments.find(s=>s.start+s.l>=d)||segments.at(-1);return s.a.clone().lerp(s.b,(d-s.start)/s.l)}
function startTour(){document.activeElement?.blur();camera.fov=68;camera.updateProjectionMatrix();tween=null;touring=true;paused=false;tourDistance=nodeDistances[selected];controls.enabled=false;document.body.classList.add('touring');$('tour').textContent='■ 退出漫游';$('overview').textContent='退出漫游';$('view-name').textContent='WALKTHROUGH / 主线漫游';toast('主线漫游 · 空格暂停 / 继续 · Esc 退出');}
function stopTour(reset=true){if(!touring)return;camera.fov=innerWidth<650?52:39;camera.updateProjectionMatrix();touring=false;paused=false;controls.enabled=true;document.body.classList.remove('touring');$('tour').textContent='▶ 沿主线漫游';$('overview').textContent='全景';if(reset)setView('overview')}
$('tour').onclick=()=>touring?stopTour():startTour();window.addEventListener('keydown',e=>{if(e.code==='Space'&&touring){e.preventDefault();paused=!paused;toast(paused?'漫游已暂停 · 空格继续':'继续漫游')}if(e.code==='Escape'&&touring)stopTour()});
$('export').onclick=async()=>{toast('正在导出低模场景…');try{const exporter=new GLTFExporter();let old=cutParts.map(o=>o.visible);cutParts.forEach(o=>o.visible=true);const glb=await exporter.parseAsync(model,{binary:true});cutParts.forEach((o,i)=>o.visible=old[i]);const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([glb],{type:'model/gltf-binary'}));a.download='Ashbell-Sanctuary.glb';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('已导出 GLB，可导入 Blender / Godot / Unity')}catch(e){toast('导出失败：'+e.message)}};
window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.fov=touring?68:innerWidth<650?52:39;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);if(!touring)setView(view)});controls.addEventListener('start',()=>{tween=null});
select(0);const clock=new THREE.Clock();let elapsed=0;function frame(){requestAnimationFrame(frame);let dt=Math.min(clock.getDelta(),.05);elapsed+=dt;if(tween){tween.t=Math.min(1,tween.t+dt*.85);let t=tween.t*tween.t*(3-2*tween.t);camera.position.lerpVectors(tween.from,tween.to,t);controls.target.lerpVectors(tween.startTarget,tween.target,t);if(tween.t===1)tween=null}if(touring){if(!paused)tourDistance+=dt*4.2;const pos=sample(tourDistance),ahead=sample(Math.min(total,tourDistance+4));pos.y+=1.85;ahead.y+=1.7;camera.position.copy(pos);camera.lookAt(ahead);let idx=0;nodeDistances.forEach((d,i)=>{if(tourDistance>=d)idx=i});$('view-description').textContent=`${String(idx+1).padStart(2,'0')} / ${nodes[idx].name}  ·  ${Math.min(100,Math.floor(tourDistance/total*100))}%  ·  空格暂停 / Esc 退出`;if(tourDistance>=total){stopTour();select(8);toast('朝圣结束。回望起点，整条旅程都折叠在这座修道院里。')}}else controls.update();
 if(unlocked)elevator.position.y=17.8+10*Math.cos(elapsed*.45);else elevator.position.y=27.8;flames.forEach((f,i)=>{f.rotation.y=elapsed*.7;f.scale.y=1.7+Math.sin(elapsed*5+i)*.2});selectRing.rotation.z=elapsed*.13;
 markers.forEach((e,i)=>{let n=nodes[i];let p=new THREE.Vector3(n.p[0],n.p[1]+(i===6?17:i===8?6:3),n.p[2]);p.project(camera);let x=(p.x*.5+.5)*innerWidth,y=(-p.y*.5+.5)*innerHeight;if(view==='top'&&i===1){x+=58;y+=12;}e.style.left=x+'px';e.style.top=y+'px';const left=innerWidth<650?180:innerWidth<1050?245:300;const right=innerWidth>1050?innerWidth-235:innerWidth-10;const visible=p.z<1&&p.z>-1&&y>95&&y<innerHeight-158&&x>left&&x<right;e.style.opacity=visible?'1':'0';e.style.pointerEvents=visible?'auto':'none'});renderer.render(scene,camera)}frame();
window.ashbell={version:2,nodes,chains,shortcuts,branches,tunnelCuts,getElevator:()=>elevator,inspect:(position,target)=>fly(position,target),getState:()=>({selected,unlocked,cut,bright,routeVisible,touring,paused,tourDistance,total,meshes:renderer.info.render.calls}),getModel:()=>model};
